Allow patching games running on LOVE2D 12, or otherwise using luaL_loadbufferx
ethangreen-dev/lovely-injector pull request #70
Opened 2024-07-29 06:09 UTC by tetraminus

I have a whole 5 hours saga behind this. Generally, the entire system has been ported to use luaL_loadbufferx instead of luaL_loadbuffer. on the Balatro side, this should change nothing. the game already used it internally.  Games on newer versions of love like love 12 should now work properly. tested with no issues on Mac and Windows, with both Balatro (Love 11.5) and the Beatblock demo(Love 12.0)

2024-07-29 06:11 UTC, tetraminus commented
Closes #69

2024-07-31 05:31 UTC, ethangreen-dev requested changes
Looks great, nice work! My changes are pretty minor, shouldn't be too annoying.

2024-07-31 05:31 UTC, ethangreen-dev commented on crates/lovely-core/src/patch/module.rs
> +        lual_loadbuffer(state, buf_cstr.into_raw() as _, buf_len as _, name_cstr.into_raw() as _, null());
Code style: Replace `null()` with `ptr::null()` both here and everywhere else.

2024-07-31 05:31 UTC, ethangreen-dev commented on crates/lovely-mac/src/lib.rs
> +// we can do this on mac because nothing matters in this world except my pain
Agreed, but either remove or replace the comment with a _why_ your pain is warranted. :-)

2024-07-31 05:31 UTC, ethangreen-dev commented on crates/lovely-mac/Cargo.toml
> +log = "0.4.21"
Unless I'm missing something you shouldn't need this - leftover from earlier development?

2024-07-31 05:31 UTC, ethangreen-dev commented on crates/lovely-win/src/lib.rs
> +        .unwrap();
AFAIK general code style has these on the same column as the previous ending parentheses.

2024-07-31 05:31 UTC, ethangreen-dev commented on crates/lovely-win/Cargo.toml
> +log = "0.4.21"
Ditto from above, this doesn't seem to be necessary? I could be missing something because it's absolutely late.

2024-07-31 05:31 UTC, ethangreen-dev commented on Cargo.lock
Make sure to recommit this after you've replaced the the log deps, if relevant.

2024-07-31 05:33 UTC, ethangreen-dev commented
And a general heads up that this will likely be merged _after_ PR #68, so you might need to rebase and resolve some merge conflicts.

2024-08-21 13:30 UTC, erenkarakal commented
when will this be merged?

2024-09-04 01:39 UTC, ethangreen-dev approved these changes

2024-09-04 01:39 UTC, merged