Update README.md path for Steam Deck
ethangreen-dev/lovely-injector pull request #93
Opened 2024-12-11 02:41 UTC by drgrib

2025-01-09 11:45 UTC, antipatico commented
I would like to add that native linux path is `$HOME/.config/Balatro/Mods`

2025-01-09 17:09 UTC, drgrib commented
@antipatico I initiated this change from Github and am not sure how to update the file. Can I get a review on this @ethangreen-dev?

2025-01-13 08:21 UTC, ethangreen-dev requested changes

2025-01-13 08:21 UTC, ethangreen-dev commented on README.md
> +3. Put one or more mods into the mod directory (NOT the same as the game directory). This should be `%AppData%/Balatro/Mods`, if you are modding Balatro ([`Home/.steam/steam/steamapps/compatdata/2379
My only real critique is that `Home/` should be replaced with `~/`, otherwise this looks good. It makes the install guide a little more difficult to read but we should probably improve that by moving it over to a dedicated wiki page.

2025-01-13 08:21 UTC, ethangreen-dev commented
Sorry about the delay - I tend to put off documentation PRs because they're so opinionated.

2025-01-13 14:30 UTC, drgrib commented on README.md
> +3. Put one or more mods into the mod directory (NOT the same as the game directory). This should be `%AppData%/Balatro/Mods`, if you are modding Balatro ([`Home/.steam/steam/steamapps/compatdata/2379
Thanks. I added your changes and also @antipatico's, now in a bulleted list for all the Windows + Proton / Wine platforms. I think this is a more intuitive way to organize the instruction and should be easier to read.

2025-01-13 14:37 UTC, drgrib commented on README.md
> +3. Put one or more mods into the mod directory (NOT the same as the game directory). This should be `%AppData%/Balatro/Mods`, if you are modding Balatro ([`Home/.steam/steam/steamapps/compatdata/2379
One note: why exactly do you think `Home/` should be replaced with `~/`? As you can see in the Steam Deck interface is the guide I linked, the directory is clearly marked as `Home/`, so I think this change will be confusing to users:
![CleanShot 2025-01-13 at 06 33 15@2x](https://github.com/user-attachments/assets/2406cae8-9b01-4a92-8dfd-062bb3b4cff6)

I've changed the path back `Home/` in anticipation that you will agree but I can change it back to `~/` if you insist on the change as contingent for your approval.

2025-01-13 14:47 UTC, drgrib commented on README.md
> +3. Put one or more mods into the mod directory (NOT the same as the game directory). This should be `%AppData%/Balatro/Mods`, if you are modding Balatro ([`Home/.steam/steam/steamapps/compatdata/2379
I also added a note about `~/` being *Home* if you are editing in the GUI.

2025-01-14 03:47 UTC, ethangreen-dev commented on README.md
> +* `$HOME/.config/Balatro/Mods` on Linux
We'll add this to our Linux native install instructions (when they're written).

2025-01-14 03:47 UTC, ethangreen-dev commented on README.md
> +* `$HOME/.config/Balatro/Mods` on Linux
(line 14)

2025-01-14 03:48 UTC, ethangreen-dev requested changes
Couple more changes

2025-01-14 04:29 UTC, drgrib commented on README.md
> +* `$HOME/.config/Balatro/Mods` on Linux
Done

2025-01-14 04:30 UTC, drgrib commented
I only saw one change. Did I miss anything?

2025-01-14 06:15 UTC, ethangreen-dev commented
Nope, I'm just a silly goof

2025-01-14 06:15 UTC, ethangreen-dev approved these changes
LGTM, nice work!

2025-01-14 06:15 UTC, merged